# Site settings
title: Erik Kallen
#email: info@erikkallen.nl
description: > # this means to ignore newlines until "baseurl:"
  This is my personal site with random projects that make up my day aside from my job.
  I have intersts in metal working, electronics, programming, backyard foundries 3D printing and other ways of tinkering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erikkallen.nl" # the base hostname & protocol for your site
twitter_username: edeuxk
github_username:  erikkallen
googleplus_username: erikkallen
linkedin_username: erikkallen
keybase_username: erikkallen
collections:
    projects:
        output: true
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-gist

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
